name: pytest
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
      - name: install poetry
        run: pip install poetry
      - name: install dependences
        run: poetry install
      - name: run pytest
        run: poetry run pytest
